"""Add orders and returns tables

Revision ID: 8bb061a81cbc
Revises: ff4b173406d7
Create Date: 2026-07-03 12:58:24.726613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bb061a81cbc'
down_revision: Union[str, Sequence[str], None] = 'ff4b173406d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_number', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'received', 'refunded', name='returnstatus', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_returns_user_status', 'returns', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_returns_order_id'), 'returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_returns_return_number'), 'returns', ['return_number'], unique=True)
    op.create_index(op.f('ix_returns_user_id'), 'returns', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_returns_user_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_return_number'), table_name='returns')
    op.drop_index(op.f('ix_returns_order_id'), table_name='returns')
    op.drop_index('idx_returns_user_status', table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index('idx_orders_user_status', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
